using Gurobi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PowerSystemPlanning.OPF
{
    /// <summary>
    /// Solves the simple economic dispatch problem for a power system.
    /// </summary>
    public class EconomicDispatch
    {
        PowerSystem powerSystem;
        GRBModel model;
        GRBEnv env;
        GRBVar[] PGen;
        GRBConstr PowerBalance;

        /// <summary>
        /// Gets the power generated by each generator in the current solution of the economic dispatch.
        /// </summary>
        public double[] PGen_Solution
        {
            get
            {
                return this.model.Get(GRB.DoubleAttr.X, this.PGen);
            }
        }

        /// <summary>
        /// Gets the total generation cost in the current solution of the economic dispatch.
        /// </summary>
        public double TotalGenerationCost
        {
            get
            {
                return this.model.Get(GRB.DoubleAttr.ObjVal);
            }
        }

        public EconomicDispatch(PowerSystem powerSystem)
        {
            this.powerSystem = powerSystem;
            this.env = new GRBEnv();
            this.model = new GRBModel(env);
            // Add variables to Gurobi model: power generated by each generator
            PGen = new GRBVar[powerSystem.NumberOfGeneratingUnits];
            double[] coeffsPGenInPowerBalance = new double[powerSystem.NumberOfGeneratingUnits];
            for (int i = 0; i < powerSystem.NumberOfGeneratingUnits; i++)
            {
                GeneratingUnit gen = powerSystem.generatingUnits[i];
                PGen[i] = model.AddVar(0, gen.InstalledCapacityMW, gen.MarginalCost, GRB.CONTINUOUS, "PGen" + gen.Id);
                coeffsPGenInPowerBalance[i] = 1;
            }
            this.model.Update();
            // Sets objective: minimize total generation costs
            this.model.Set(GRB.IntAttr.ModelSense, GRB.MINIMIZE);
            // Creates power balance constraint
            GRBLinExpr powerBalanceLHS = new GRBLinExpr();
            powerBalanceLHS.AddTerms(coeffsPGenInPowerBalance, PGen);
            GRBLinExpr powerBalanceRHS = new GRBLinExpr();
            powerBalanceRHS.AddConstant(powerSystem.TotalMWInelasticLoads);
            this.PowerBalance = model.AddConstr(null, GRB.EQUAL, null, "PowerBalance");
        }

        public void Solve()
        {
            this.model.Optimize();
        }

        public void Dispose()
        {
            // Dispose of Gurobi model and env
            model.Dispose();
            env.Dispose();
        }
    }
}
